application: geekintheloftcloud
version: 1
runtime: php
api_version: 1
threadsafe: true

handlers:
- url: /(.*\.(bmp|gif|ico|jpeg|jpg|png))
  static_files: \1
  mime_type: (img/jpg|img/png)
  upload: (.*\.(bmp|gif|ico|jpeg|jpg|png))

- url: /css
  static_dir: css

- url: /js
  static_dir: js

- url: /fonts
  static_dir: fonts

- url: /img
  static_dir: img

- url: /(.*\.(php|html))
  script: \1

- url: /.*
  script: main.html