"""empty message

Revision ID: 2d5a499b63ef
Revises: 6a8aef0420b
Create Date: 2014-09-18 20:19:50.071000

"""

# revision identifiers, used by Alembic.
revision = '2d5a499b63ef'
down_revision = '6a8aef0420b'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
