"""empty message

Revision ID: 3828595214df
Revises: 580b7a6a6440
Create Date: 2014-08-24 14:58:35.696000

"""

# revision identifiers, used by Alembic.
revision = '3828595214df'
down_revision = '580b7a6a6440'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('comment')
    op.drop_table('article')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('article',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('title', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('content', mysql.TEXT(), nullable=True),
    sa.Column('author', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('category', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('date_created', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset=u'utf8',
    mysql_engine=u'InnoDB'
    )
    op.create_table('comment',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('article_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('author', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('email', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('password', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('content', mysql.TEXT(), nullable=True),
    sa.Column('date_created', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['article_id'], [u'article.id'], name=u'comment_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset=u'utf8',
    mysql_engine=u'InnoDB'
    )
    ### end Alembic commands ###
