"""empty message

Revision ID: 39b97d83d195
Revises: None
Create Date: 2014-12-09 11:39:35.858858

"""

# revision identifiers, used by Alembic.
revision = '39b97d83d195'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('birthday', sa.DateTime(), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('page_domain', sa.String(length=255), nullable=True),
    sa.Column('subscribe', sa.Integer(), nullable=True),
    sa.Column('profile', sa.String(length=1024), nullable=True),
    sa.Column('genre', sa.String(length=255), nullable=True),
    sa.Column('img_key', sa.String(length=255), nullable=True),
    sa.Column('join_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('email'),
    sa.UniqueConstraint('page_domain')
    )
    op.create_table('history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('content', sa.String(length=255), nullable=True),
    sa.Column('tag', sa.String(length=255), nullable=True),
    sa.Column('starttime', sa.String(length=255), nullable=True),
    sa.Column('endtime', sa.String(length=255), nullable=True),
    sa.Column('user_email', sa.String(length=255), nullable=True),
    sa.Column('comments', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['user_email'], ['user.email'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('history')
    op.drop_table('user')
    ### end Alembic commands ###
