"""empty message

Revision ID: 39e5e4b134e
Revises: 265891851bfd
Create Date: 2014-09-27 12:49:02.312000

"""

# revision identifiers, used by Alembic.
revision = '39e5e4b134e'
down_revision = '265891851bfd'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('page_domain', sa.String(length=255), nullable=False))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'page_domain')
    ### end Alembic commands ###
