"""empty message

Revision ID: 3a0ef200fc71
Revises: 2d5a499b63ef
Create Date: 2014-09-19 02:39:06.394000

"""

# revision identifiers, used by Alembic.
revision = '3a0ef200fc71'
down_revision = '2d5a499b63ef'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('profile', sa.String(length=1024), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'profile')
    ### end Alembic commands ###
