"""empty message

Revision ID: 3b27563e820c
Revises: 3f92c5872bc7
Create Date: 2014-09-21 21:18:06.035000

"""

# revision identifiers, used by Alembic.
revision = '3b27563e820c'
down_revision = '3f92c5872bc7'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
