"""empty message

Revision ID: 3f92c5872bc7
Revises: 532eddd07b27
Create Date: 2014-09-21 17:10:30.944000

"""

# revision identifiers, used by Alembic.
revision = '3f92c5872bc7'
down_revision = '532eddd07b27'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
