"""empty message

Revision ID: 503658c1f149
Revises: 3a0ef200fc71
Create Date: 2014-09-19 02:59:43.029000

"""

# revision identifiers, used by Alembic.
revision = '503658c1f149'
down_revision = '3a0ef200fc71'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('age', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'age')
    ### end Alembic commands ###
