"""empty message

Revision ID: 532eddd07b27
Revises: 503658c1f149
Create Date: 2014-09-21 16:46:40.247000

"""

# revision identifiers, used by Alembic.
revision = '532eddd07b27'
down_revision = '503658c1f149'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('birthday', sa.String(length=255), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'birthday')
    ### end Alembic commands ###
